// Optional real-browser smoke check: node tests/outside-browser.cjs
const { spawn } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const assert = require('node:assert/strict');
const { pathToFileURL } = require('node:url');
const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
const profile = fs.mkdtempSync(path.join(os.tmpdir(), 'cracks-exterior-'));
const chrome = process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe';
const child = spawn(chrome, ['--headless=new', '--disable-gpu', '--no-first-run', '--remote-debugging-port=0', '--user-data-dir='+profile, '--window-size=1600,1000', pathToFileURL(path.resolve(__dirname, '../index.html')).href], { windowsHide: true });
let log = '';
child.stderr.on('data', chunk => { log += chunk; });
(async () => {
  let socket;
  try {
    for(let i=0;i<100 && !/DevTools listening on (ws:\/\/[^\s]+)/.test(log);i++) await delay(100);
    const endpoint = log.match(/DevTools listening on (ws:\/\/[^\s]+)/)?.[1];
    assert.ok(endpoint, 'Chrome debugging endpoint must start');
    const origin = new URL(endpoint).origin.replace('ws:', 'http:');
    const pages = await (await fetch(origin+'/json/list')).json();
    const page = pages.find(page => page.type === 'page');
    socket = new WebSocket(page.webSocketDebuggerUrl);
    await new Promise(resolve => socket.addEventListener('open', resolve, { once: true }));
    let sequence = 0;
    const pending = new Map();
    socket.addEventListener('message', event => {
      const message = JSON.parse(event.data);
      if (pending.has(message.id)) { pending.get(message.id)(message); pending.delete(message.id); }
    });
    const call = (method, params = {}) => new Promise(resolve => {
      const id = ++sequence; pending.set(id, resolve); socket.send(JSON.stringify({ id, method, params }));
    });
    const evaluate = async expression => {
      const result = await call('Runtime.evaluate', { expression, returnByValue: true, awaitPromise: true });
      assert.ok(!result.result.exceptionDetails, JSON.stringify(result));
      return result.result.result.value;
    };
    await delay(800);
    assert.equal(await evaluate('typeof outsideRoute'), 'function');
    const output = path.resolve(__dirname, '../output');
    fs.mkdirSync(output, { recursive: true });
    const capture = async name => {
      const result = await call('Page.captureScreenshot', { format: 'png' });
      fs.writeFileSync(path.join(output, name), Buffer.from(result.result.data, 'base64'));
    };
    await evaluate("titleScreen.hidden=true; game.inert=false; document.body.classList.add('game-started'); Object.assign(gameState,{curtainsOpen:false,lampOn:false,bedroomMainLightOn:false}); showRoom('bedroom'); movement.x=42; movement.y=84; renderPlayer(); messageBox.classList.add('hidden');");
    await delay(700);
    assert.match(await evaluate("getComputedStyle(document.getElementById('room-background')).backgroundImage"), /bedroom-c0-l0-m0/);
    await capture('lighting-bedroom-dark.png');
    await evaluate("toggleLight('bedroomMain');");
    const immediateBedroomFrame = await evaluate("getComputedStyle(document.getElementById('room-background')).backgroundImage");
    assert.match(immediateBedroomFrame, /bedroom-c0-l0-m[01]/, 'a decoded old or new bedroom frame must remain visible during the swap');
    assert.notEqual(immediateBedroomFrame, 'none');
    await delay(40);
    const lightSwapCoverage = await evaluate("[...document.querySelectorAll('.room-background-layer')].filter(layer => layer.classList.contains('is-visible')).map(layer => Number(getComputedStyle(layer).opacity))");
    assert.equal(lightSwapCoverage.length, 2, 'the incoming and outgoing frames must overlap during a light switch');
    assert.equal(Math.max(...lightSwapCoverage), 1, 'one full-screen frame must remain fully opaque throughout the swap');
    assert.match(await evaluate("getComputedStyle(document.getElementById('player')).transitionDuration"), /0\.2s/, 'character illumination must transition in 0.20 seconds');
    await delay(300);
    assert.equal(await evaluate("document.querySelectorAll('.room-background-layer.is-visible').length"), 1, 'the outgoing frame must be released only after the reveal');
    assert.match(await evaluate("getComputedStyle(document.getElementById('room-background')).backgroundImage"), /bedroom-c0-l0-m1/);
    await capture('lighting-bedroom-main.png');
    await evaluate("positionDoor(apartmentRooms.bedroom.objects.door);document.getElementById('doorway').dataset.motion='opening';document.getElementById('door-face').style.transform='rotateY(55deg)'");
    assert.deepEqual(await evaluate("['left','top','width','height'].map(key => document.getElementById('doorway').style[key])"), ['72.9665%','13.9214%','9.5096%','42.8268%']);
    assert.equal(await evaluate("getComputedStyle(document.getElementById('bedroom-door-foreground')).display"), 'block');
    assert.match(await evaluate("document.getElementById('door-surface').style.backgroundImage"), /bedroom-door-states\/bedroom-c0-l0-m1\.png/);
    await capture('bedroom-door-opening-preview.png');
    await evaluate("cancelTransition()");
    await evaluate("showRoom('living');movement.x=50;movement.y=82;Object.assign(gameState,{livingCurtainsOpen:false,livingMainLightOn:false,kitchenLightsOn:false,hallwayLightOn:false});syncRoom();renderPlayer();messageBox.classList.add('hidden');");
    await delay(800);
    assert.match(await evaluate("getComputedStyle(document.getElementById('room-background')).backgroundImage"), /living-c0-m0-b0-h0/);
    await capture('lighting-living-dark.png');
    await evaluate("Object.assign(gameState,{livingCurtainsOpen:true,livingMainLightOn:true,kitchenLightsOn:true,hallwayLightOn:true});syncRoom();renderPlayer();");
    await delay(800);
    assert.match(await evaluate("getComputedStyle(document.getElementById('room-background')).backgroundImage"), /living-c1-m1-b1-h1/);
    assert.match(await evaluate("getComputedStyle(document.querySelector('#living-toaster .is-visible')).backgroundImage"), /living-c1-m1-b1-h1/);
    assert.equal(await evaluate("getComputedStyle(document.getElementById('living-toaster')).display"), 'block');
    await capture('lighting-living-all-on.png');
    await evaluate("setVerb('use');interact('toaster','use');messageBox.classList.add('hidden');");
    assert.equal(await evaluate('gameState.toasterTaken'), true);
    assert.equal(await evaluate("getComputedStyle(document.getElementById('living-toaster')).display"), 'none');
    await capture('lighting-living-toaster-taken.png');
    await evaluate("interact('toaster','use');messageBox.classList.add('hidden');");
    assert.equal(await evaluate('gameState.toasterTaken'), false);
    assert.equal(await evaluate("getComputedStyle(document.getElementById('living-toaster')).display"), 'block');
    await evaluate("showRoom('bathroom');movement.x=50;movement.y=78;Object.assign(gameState,{bathroomCurtainsOpen:false,bathroomMainLightOn:false});syncRoom();renderPlayer();messageBox.classList.add('hidden');");
    await delay(800);
    assert.match(await evaluate("getComputedStyle(document.getElementById('room-background')).backgroundImage"), /bathroom-c0-m0/);
    await capture('lighting-bathroom-dark.png');
    const closedBathroom = await evaluate("getComputedStyle(document.getElementById('room-background')).backgroundImage");
    await evaluate("Object.assign(gameState,{bathroomCurtainsOpen:true,bathroomMainLightOn:true});syncRoom();renderPlayer();");
    await delay(800);
    const openBathroom = await evaluate("getComputedStyle(document.getElementById('room-background')).backgroundImage");
    assert.match(openBathroom, /bathroom-c1-m1/);
    assert.notEqual(openBathroom, closedBathroom);
    await capture('lighting-bathroom-daylight-main.png');
    await evaluate("showRoom('living');Object.assign(gameState,{livingCurtainsOpen:true,livingMainLightOn:false,kitchenLightsOn:false,hallwayLightOn:true});movement.x=91;movement.y=54;syncRoom();renderPlayer();interact('exit','open');");
    await delay(1000);
    assert.equal(await evaluate('gameState.currentRoom'), 'living');
    assert.ok(await evaluate("parseFloat(document.getElementById('player').style.getPropertyValue('--sprite-width'))") < 18);
    await capture('living-hallway-scale-preview.png');
    for (let i=0; i<12 && await evaluate('gameState.currentRoom') !== 'outside'; i++) await delay(100);
    assert.equal(await evaluate('gameState.currentRoom'), 'outside');
    assert.equal(await evaluate("document.getElementById('doorway').dataset.hinge"), 'left');
    assert.match(await evaluate("document.getElementById('door-face').style.transform"), /rotateY\([1-9]/);
    assert.match(await evaluate("document.getElementById('door-surface').style.backgroundImage"), /outside_bg\.png/);
    await capture('outside-door-closing-preview.png');
    await delay(1500);
    assert.equal(await evaluate('gameState.currentRoom'), 'outside');
    assert.equal(await evaluate('transition'), null);
    assert.ok(Math.abs(await evaluate("parseFloat(document.getElementById('player').style.getPropertyValue('--sprite-width'))") - 10.2) < .001);
    await evaluate("messageBox.classList.add('hidden');");
    await delay(300);
    await capture('outside-patio-preview.png');
    await evaluate("movePlayerTo(74,49);");
    await delay(750);
    assert.equal(await evaluate('!!movement.destination.stairs'), true);
    await capture('outside-stairs-preview.png');
    await delay(1800);
    await evaluate("movePlayerTo(72.7,92);");
    await delay(2600);
    assert.equal(await evaluate('movement.destination'), null);
    assert.ok(Math.abs(await evaluate('movement.x') - 72.7) < .001);
    assert.equal(await evaluate('movement.y'), 92);
    assert.ok(Math.abs(await evaluate("parseFloat(document.getElementById('player').style.getPropertyValue('--sprite-width'))") - 22.4) < .001);
    await capture('outside-between-cars-preview.png');
    await evaluate("movePlayerTo(91,90);");
    await delay(1800);
    assert.equal(await evaluate('movement.destination'), null);
    assert.ok(Math.abs(await evaluate('movement.x') - 91) < .001);
    assert.ok(Math.abs(await evaluate('movement.y') - 90) < .001);
    await evaluate("movePlayerTo(42,72);");
    await delay(5000);
    assert.equal(await evaluate('movement.destination'), null);
    assert.ok(Math.abs(await evaluate('movement.x') - 42) < .001);
    assert.ok(Math.abs(await evaluate('movement.y') - 72) < .001);
    await capture('outside-free-parking-preview.png');
    await evaluate("movePlayerTo(72.7,70);");
    await delay(6000);
    assert.equal(await evaluate('movement.destination'), null);
    assert.equal(await evaluate("document.getElementById('scene').classList.contains('player-behind-cars')"), true);
    await capture('outside-car-mask-preview.png');
    await evaluate("handleTarget('frontDoor');");
    await delay(8000);
    assert.equal(await evaluate('gameState.currentRoom'), 'living');
    console.log('Browser checks passed: decoded lighting swaps, perspective scale, front door, patio, stairs, car passages, free parking-lot movement and return. Screenshots saved in output/.');
  } finally {
    socket?.close();
    child.kill();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
