param([string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing
Add-Type -ReferencedAssemblies System.Drawing -TypeDefinition @"
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
public static class ReferenceShapedCollarRegeneratedOutfitBuilder {
  static bool StrongKey(Color c){int other=Math.Max(c.R,c.B);return c.G>170&&c.G-other>78&&c.G>c.R*1.35&&c.G>c.B*1.35;}
  static bool EdgeKey(Color c){int other=Math.Max(c.R,c.B);return c.G>145&&c.G-other>58&&c.G>c.R*1.22&&c.G>c.B*1.22;}
  static bool Skin(Color c){return c.A>0&&c.R>120&&c.G>50&&c.R-c.G>25&&c.R-c.B>35&&c.G-c.B>4;}
  static bool Hair(Color c){return c.A>0&&c.R>42&&c.R<190&&c.R>c.G*1.12&&c.G>c.B*1.03&&c.B<105;}
  static bool Identity(Color c){return Skin(c)||Hair(c);}
  static bool FleshEdge(Color c){return Skin(c)||(c.A>0&&c.R>105&&c.R>c.G+10&&c.R>c.B+10);}
  static bool Shirt(Color c,bool clean){if(c.A==0)return false;return clean?(c.G>c.R+8&&c.G>c.B+2):(c.B>c.R+8&&c.B>c.G+2);}
  static bool DarkGarment(Color c){if(c.A==0)return false;int hi=Math.Max(c.R,Math.Max(c.G,c.B)),lo=Math.Min(c.R,Math.Min(c.G,c.B));return (c.R+c.G+c.B)/3<115&&hi-lo<70;}
  static bool NearIdentity(Bitmap image,int x,int y,int x0,int x1,int y0,int y1){for(int yy=Math.Max(y0,y-1);yy<=Math.Min(y1,y+1);yy++)for(int xx=Math.Max(x0,x-1);xx<=Math.Min(x1,x+1);xx++)if(Identity(image.GetPixel(xx,yy)))return true;return false;}
  static Bitmap Key(string sourcePath){using(Bitmap loaded=new Bitmap(sourcePath)){int width=Math.Min(1619,loaded.Width),height=Math.Min(971,loaded.Height);Bitmap output=new Bitmap(width,height,PixelFormat.Format32bppArgb);using(Graphics g=Graphics.FromImage(output)){g.DrawImageUnscaled(loaded,0,0);}bool[,] removed=new bool[width,height];for(int y=0;y<height;y++)for(int x=0;x<width;x++)if(StrongKey(output.GetPixel(x,y)))removed[x,y]=true;for(int pass=0;pass<2;pass++){var add=new List<int>();for(int y=0;y<height;y++)for(int x=0;x<width;x++)if(!removed[x,y]&&EdgeKey(output.GetPixel(x,y))){bool near=false;for(int yy=Math.Max(0,y-1);yy<=Math.Min(height-1,y+1)&&!near;yy++)for(int xx=Math.Max(0,x-1);xx<=Math.Min(width-1,x+1);xx++)if(removed[xx,yy]){near=true;break;}if(near)add.Add(y*width+x);}foreach(int v in add)removed[v%width,v/width]=true;}for(int y=0;y<height;y++)for(int x=0;x<width;x++)if(removed[x,y])output.SetPixel(x,y,Color.Transparent);for(int y=0;y<height;y++)for(int x=0;x<width;x++){Color c=output.GetPixel(x,y);if(c.A==0)continue;bool edge=false;for(int yy=Math.Max(0,y-2);yy<=Math.Min(height-1,y+2)&&!edge;yy++)for(int xx=Math.Max(0,x-2);xx<=Math.Min(width-1,x+2);xx++)if(output.GetPixel(xx,yy).A==0){edge=true;break;}if(edge&&c.G-Math.Max(c.R,c.B)>24){int green=Math.Min(c.G,Math.Max(c.R,c.B)+10);output.SetPixel(x,y,Color.FromArgb(255,c.R,green,c.B));}}return output;}}
  static void HeadBox(Bitmap image,int x0,int x1,int y0,int fh,out int minX,out int maxX,out int minY,out int scanBottom,out int skinBottom){scanBottom=y0+(int)(fh*.19);minX=x1+1;maxX=x0-1;minY=scanBottom;skinBottom=y0;for(int y=y0;y<=scanBottom;y++)for(int x=x0;x<=x1;x++){Color c=image.GetPixel(x,y);if(c.A>0){minX=Math.Min(minX,x);maxX=Math.Max(maxX,x);minY=Math.Min(minY,y);}if(Skin(c))skinBottom=Math.Max(skinBottom,y);}int lower=y0+(int)(fh*.245);for(int y=scanBottom+1;y<=lower;y++)for(int x=Math.Max(x0,minX-5);x<=Math.Min(x1,maxX+5);x++)if(Skin(image.GetPixel(x,y)))skinBottom=Math.Max(skinBottom,y);}
  static void CanonicalHead(Bitmap output,Bitmap canonical,Bitmap raw){int width=output.Width,height=output.Height;for(int row=0;row<3;row++)for(int col=0;col<5;col++){int x0=(int)Math.Round(col*width/5.0),x1=(int)Math.Round((col+1)*width/5.0)-1,y0=(int)Math.Round(row*height/3.0),y1=(int)Math.Round((row+1)*height/3.0)-1,fh=y1-y0+1;int cMin,cMax,cTop,cScan,cSkinBottom,gMin,gMax,gTop,gScan,gSkinBottom;HeadBox(canonical,x0,x1,y0,fh,out cMin,out cMax,out cTop,out cScan,out cSkinBottom);HeadBox(output,x0,x1,y0,fh,out gMin,out gMax,out gTop,out gScan,out gSkinBottom);int cleanBottom=Math.Min(gSkinBottom,cSkinBottom)-5;for(int y=Math.Max(y0,gTop-3);y<=Math.Min(y1,cleanBottom);y++){int left=x1+1,right=x0-1;for(int x=Math.Max(x0,gMin-8);x<=Math.Min(x1,gMax+8);x++)if(Identity(output.GetPixel(x,y))){left=Math.Min(left,x);right=Math.Max(right,x);}if(right>=left)for(int x=Math.Max(x0,left-3);x<=Math.Min(x1,right+3);x++)output.SetPixel(x,y,Color.Transparent);}for(int sy=Math.Max(y0,cTop-3);sy<=Math.Min(y1,cSkinBottom);sy++){int left=x1+1,right=x0-1;for(int sx=Math.Max(x0,cMin-8);sx<=Math.Min(x1,cMax+8);sx++)if(Identity(canonical.GetPixel(sx,sy))){left=Math.Min(left,sx);right=Math.Max(right,sx);}if(right>=left)for(int sx=Math.Max(x0,left-3);sx<=Math.Min(x1,right+3);sx++){Color a=canonical.GetPixel(sx,sy);bool copy=sy<=cSkinBottom-5?(a.A>0&&NearIdentity(canonical,sx,sy,x0,x1,y0,y1)):Skin(a);if(copy)output.SetPixel(sx,sy,a);}}int sumR=0,sumG=0,sumB=0,samples=0;for(int sy=Math.Max(y0,cSkinBottom-18);sy<=Math.Max(y0,cSkinBottom-6);sy++)for(int sx=Math.Max(x0,cMin-8);sx<=Math.Min(x1,cMax+8);sx++){Color c=canonical.GetPixel(sx,sy),r=raw.GetPixel(sx,sy);if(Skin(c)&&Skin(r)){sumR+=c.R-r.R;sumG+=c.G-r.G;sumB+=c.B-r.B;samples++;}}int shiftR=samples>0?(int)Math.Round(sumR/(double)samples):0,shiftG=samples>0?(int)Math.Round(sumG/(double)samples):0,shiftB=samples>0?(int)Math.Round(sumB/(double)samples):0;for(int sy=Math.Max(y0,cSkinBottom-10);sy<=Math.Min(y1,cSkinBottom+10);sy++)for(int sx=Math.Max(x0,cMin-12);sx<=Math.Min(x1,cMax+12);sx++){Color r=raw.GetPixel(sx,sy);if(sy<cSkinBottom-7){if(r.A>0&&!Skin(r)&&!Hair(r))output.SetPixel(sx,sy,r);continue;}if(r.A==0){output.SetPixel(sx,sy,Color.Transparent);continue;}if(Skin(r)){int rr=Math.Max(0,Math.Min(255,r.R+shiftR)),gg=Math.Max(0,Math.Min(255,r.G+shiftG)),bb=Math.Max(0,Math.Min(255,r.B+shiftB));Color c=canonical.GetPixel(sx,sy);if(Skin(c)&&sy<=cSkinBottom-4){int weight=Math.Max(1,Math.Min(4,sy-(cSkinBottom-8)));rr=(c.R*(4-weight)+rr*weight+2)/4;gg=(c.G*(4-weight)+gg*weight+2)/4;bb=(c.B*(4-weight)+bb*weight+2)/4;}output.SetPixel(sx,sy,Color.FromArgb(r.A,rr,gg,bb));}else output.SetPixel(sx,sy,r);}int silhouetteBottom=Math.Max(y0,cSkinBottom-8);for(int sy=y0;sy<=silhouetteBottom;sy++)for(int sx=Math.Max(x0,cMin-10);sx<=Math.Min(x1,cMax+10);sx++)if(canonical.GetPixel(sx,sy).A==0)output.SetPixel(sx,sy,Color.Transparent);}}
  static void RepairFrontCollars(Bitmap image,Bitmap canonical,bool clean){int width=image.Width,height=image.Height,row=1;using(Bitmap before=image.Clone(new Rectangle(0,0,width,height),PixelFormat.Format32bppArgb)){for(int col=0;col<5;col++){int x0=(int)Math.Round(col*width/5.0),x1=(int)Math.Round((col+1)*width/5.0)-1,y0=(int)Math.Round(row*height/3.0),y1=(int)Math.Round((row+1)*height/3.0)-1,fh=y1-y0+1,cMin,cMax,cTop,cScan,cSkinBottom;HeadBox(canonical,x0,x1,y0,fh,out cMin,out cMax,out cTop,out cScan,out cSkinBottom);for(int y=Math.Max(y0,cSkinBottom-12);y<=Math.Min(y1,cSkinBottom+12);y++)for(int x=Math.Max(x0,cMin-18);x<=Math.Min(x1,cMax+18);x++){Color p=before.GetPixel(x,y);if(!FleshEdge(p))continue;int skinNeighbours=0,shirtNeighbours=0,bestScore=int.MinValue;Color best=Color.Empty;for(int yy=Math.Max(y0,y-1);yy<=Math.Min(y1,y+1);yy++)for(int xx=Math.Max(x0,x-1);xx<=Math.Min(x1,x+1);xx++){if(xx==x&&yy==y)continue;Color n=before.GetPixel(xx,yy);if(FleshEdge(n))skinNeighbours++;if(Shirt(n,clean)){shirtNeighbours++;int score=clean?n.G-Math.Max(n.R,n.B):n.B-Math.Max(n.R,n.G);if(score>bestScore){bestScore=score;best=n;}}}if(shirtNeighbours>=1&&skinNeighbours<=5)image.SetPixel(x,y,best);}}}}
  static void RepairSideShoulders(Bitmap image,Bitmap canonical){int width=image.Width,height=image.Height,row=0;using(Bitmap before=image.Clone(new Rectangle(0,0,width,height),PixelFormat.Format32bppArgb)){for(int col=0;col<5;col++){int x0=(int)Math.Round(col*width/5.0),x1=(int)Math.Round((col+1)*width/5.0)-1,y0=(int)Math.Round(row*height/3.0),y1=(int)Math.Round((row+1)*height/3.0)-1,fh=y1-y0+1,cMin,cMax,cTop,cScan,cSkinBottom;HeadBox(canonical,x0,x1,y0,fh,out cMin,out cMax,out cTop,out cScan,out cSkinBottom);int rx0=Math.Max(x0,cMin-35),rx1=Math.Min(x1,cMax+15),ry0=Math.Max(y0,cSkinBottom-12),ry1=Math.Min(y1,cSkinBottom+18);for(int y=ry0;y<=ry1;y++)for(int x=rx0;x<=rx1;x++){Color p=before.GetPixel(x,y);int dark=0,flesh=0,bestDistance=int.MaxValue;Color best=Color.Empty;for(int yy=Math.Max(y0,y-1);yy<=Math.Min(y1,y+1);yy++)for(int xx=Math.Max(x0,x-1);xx<=Math.Min(x1,x+1);xx++){if(xx==x&&yy==y)continue;Color n=before.GetPixel(xx,yy);if(FleshEdge(n))flesh++;if(DarkGarment(n)){dark++;int distance=Math.Abs(n.R-p.R)+Math.Abs(n.G-p.G)+Math.Abs(n.B-p.B);if(distance<bestDistance){bestDistance=distance;best=n;}}}if((FleshEdge(p)&&dark>=2&&flesh<=4)||(p.A==0&&dark>=5))image.SetPixel(x,y,best);}int curveTop=Math.Max(y0,cSkinBottom-18),curveBottom=Math.Min(y1,cSkinBottom-3),previousNeck=-1;for(int y=curveTop;y<=curveBottom;y++){int measured=x1+1;for(int x=Math.Max(x0,cMin-8);x<=Math.Min(x1,cMax+8);x++)if(FleshEdge(before.GetPixel(x,y))){measured=x;break;}if(measured>x1)continue;int neck=previousNeck<0?measured:Math.Max(previousNeck-1,Math.Min(previousNeck+1,measured));previousNeck=neck;int step=y-curveTop,span=Math.Max(1,curveBottom-curveTop),outside=Math.Min(4,(step+2)/4),inside=(int)Math.Round(10.0*(1.0-Math.Cos((step/(double)span)*Math.PI/2.0)));for(int tx=Math.Max(x0,neck-outside);tx<=Math.Min(x1,neck+inside);tx++){Color bestDark=Color.Empty;int bestRange=int.MaxValue;for(int yy=y;yy<=Math.Min(y1,y+10);yy++)for(int xx=Math.Max(x0,tx-7);xx<=Math.Min(x1,tx+2);xx++){Color n=before.GetPixel(xx,yy);if(!DarkGarment(n))continue;int range=Math.Abs(xx-tx)+Math.Abs(yy-y);if(range<bestRange){bestRange=range;bestDark=n;}}if(bestRange<int.MaxValue)image.SetPixel(tx,y,bestDark);}}}}}
  static void RemoveSpecks(Bitmap image){int width=image.Width,height=image.Height;for(int row=0;row<3;row++)for(int col=0;col<5;col++){int x0=(int)Math.Round(col*width/5.0),x1=(int)Math.Round((col+1)*width/5.0)-1,y0=(int)Math.Round(row*height/3.0),y1=(int)Math.Round((row+1)*height/3.0)-1;bool[,] seen=new bool[x1-x0+1,y1-y0+1];int[] dx={1,-1,0,0},dy={0,0,1,-1};for(int sy=y0;sy<=y1;sy++)for(int sx=x0;sx<=x1;sx++){if(seen[sx-x0,sy-y0]||image.GetPixel(sx,sy).A==0)continue;var comp=new List<int>();var q=new Queue<int>();q.Enqueue(sy*width+sx);seen[sx-x0,sy-y0]=true;while(q.Count>0){int v=q.Dequeue(),x=v%width,y=v/width;comp.Add(v);for(int n=0;n<4;n++){int nx=x+dx[n],ny=y+dy[n];if(nx<x0||nx>x1||ny<y0||ny>y1||seen[nx-x0,ny-y0]||image.GetPixel(nx,ny).A==0)continue;seen[nx-x0,ny-y0]=true;q.Enqueue(ny*width+nx);}}if(comp.Count<24)foreach(int v in comp)image.SetPixel(v%width,v/width,Color.Transparent);}}}  static string BuildOne(string source,string canonicalPath,string outputPath,bool clean){using(Bitmap output=Key(source))using(Bitmap canonical=new Bitmap(canonicalPath))using(Bitmap raw=output.Clone(new Rectangle(0,0,output.Width,output.Height),PixelFormat.Format32bppArgb)){CanonicalHead(output,canonical,raw);RepairFrontCollars(output,canonical,clean);RepairSideShoulders(output,canonical);RemoveSpecks(output);output.Save(outputPath,ImageFormat.Png);return String.Format("{0}: {1}x{2}, broad reference-shaped collar and feathered neck",System.IO.Path.GetFileName(outputPath),output.Width,output.Height);}}
  public static string Build(string crumpledSource,string cleanSource,string canonical,string assets){return BuildOne(crumpledSource,canonical,assets+"/unused/player-sheet-clothes-barefoot-v13.png",false)+Environment.NewLine+BuildOne(cleanSource,canonical,assets+"/unused/player-sheet-clean-barefoot-v15.png",true);}
}
"@
$assets=Join-Path $ProjectRoot 'assets'
[ReferenceShapedCollarRegeneratedOutfitBuilder]::Build((Join-Path $assets 'unused/player-crumpled-regenerated-key-v4.png'),(Join-Path $assets 'unused/player-clean-regenerated-key-v4.png'),(Join-Path $assets 'used/player-sheet-keyed-v1.png'),$assets)