param([string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing
Add-Type -ReferencedAssemblies System.Drawing -TypeDefinition @"
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
public static class ExactHeadRegeneratedOutfitBuilder {
  static bool StrongKey(Color c){int other=Math.Max(c.R,c.B);return c.G>170&&c.G-other>78&&c.G>c.R*1.35&&c.G>c.B*1.35;}
  static bool EdgeKey(Color c){int other=Math.Max(c.R,c.B);return c.G>145&&c.G-other>58&&c.G>c.R*1.22&&c.G>c.B*1.22;}
  static bool Skin(Color c){return c.A>0&&c.R>120&&c.G>50&&c.R-c.G>25&&c.R-c.B>35&&c.G-c.B>4;}
  static bool Hair(Color c){return c.A>0&&c.R>42&&c.R<190&&c.R>c.G*1.12&&c.G>c.B*1.03&&c.B<105;}
  static bool Identity(Color c){return Skin(c)||Hair(c);}
  static bool NearIdentity(Bitmap image,int x,int y,int x0,int x1,int y0,int y1){for(int yy=Math.Max(y0,y-1);yy<=Math.Min(y1,y+1);yy++)for(int xx=Math.Max(x0,x-1);xx<=Math.Min(x1,x+1);xx++)if(Identity(image.GetPixel(xx,yy)))return true;return false;}
  static Bitmap Key(string sourcePath){using(Bitmap loaded=new Bitmap(sourcePath)){int width=Math.Min(1619,loaded.Width),height=Math.Min(971,loaded.Height);Bitmap output=new Bitmap(width,height,PixelFormat.Format32bppArgb);using(Graphics g=Graphics.FromImage(output)){g.DrawImageUnscaled(loaded,0,0);}bool[,] removed=new bool[width,height];for(int y=0;y<height;y++)for(int x=0;x<width;x++)if(StrongKey(output.GetPixel(x,y)))removed[x,y]=true;for(int pass=0;pass<2;pass++){var add=new List<int>();for(int y=0;y<height;y++)for(int x=0;x<width;x++)if(!removed[x,y]&&EdgeKey(output.GetPixel(x,y))){bool near=false;for(int yy=Math.Max(0,y-1);yy<=Math.Min(height-1,y+1)&&!near;yy++)for(int xx=Math.Max(0,x-1);xx<=Math.Min(width-1,x+1);xx++)if(removed[xx,yy]){near=true;break;}if(near)add.Add(y*width+x);}foreach(int v in add)removed[v%width,v/width]=true;}for(int y=0;y<height;y++)for(int x=0;x<width;x++)if(removed[x,y])output.SetPixel(x,y,Color.Transparent);for(int y=0;y<height;y++)for(int x=0;x<width;x++){Color c=output.GetPixel(x,y);if(c.A==0)continue;bool edge=false;for(int yy=Math.Max(0,y-2);yy<=Math.Min(height-1,y+2)&&!edge;yy++)for(int xx=Math.Max(0,x-2);xx<=Math.Min(width-1,x+2);xx++)if(output.GetPixel(xx,yy).A==0){edge=true;break;}if(edge&&c.G-Math.Max(c.R,c.B)>24){int green=Math.Min(c.G,Math.Max(c.R,c.B)+10);output.SetPixel(x,y,Color.FromArgb(255,c.R,green,c.B));}}return output;}}
  static void HeadBox(Bitmap image,int x0,int x1,int y0,int fh,out int minX,out int maxX,out int minY,out int scanBottom,out int skinBottom){scanBottom=y0+(int)(fh*.19);minX=x1+1;maxX=x0-1;minY=scanBottom;skinBottom=y0;for(int y=y0;y<=scanBottom;y++)for(int x=x0;x<=x1;x++){Color c=image.GetPixel(x,y);if(c.A>0){minX=Math.Min(minX,x);maxX=Math.Max(maxX,x);minY=Math.Min(minY,y);}if(Skin(c))skinBottom=Math.Max(skinBottom,y);}int lower=y0+(int)(fh*.245);for(int y=scanBottom+1;y<=lower;y++)for(int x=Math.Max(x0,minX-5);x<=Math.Min(x1,maxX+5);x++)if(Skin(image.GetPixel(x,y)))skinBottom=Math.Max(skinBottom,y);}
  static void CanonicalHead(Bitmap output,Bitmap canonical){int width=output.Width,height=output.Height;for(int row=0;row<3;row++)for(int col=0;col<5;col++){int x0=(int)Math.Round(col*width/5.0),x1=(int)Math.Round((col+1)*width/5.0)-1,y0=(int)Math.Round(row*height/3.0),y1=(int)Math.Round((row+1)*height/3.0)-1,fh=y1-y0+1;int cMin,cMax,cTop,cScan,cSkinBottom,gMin,gMax,gTop,gScan,gSkinBottom;HeadBox(canonical,x0,x1,y0,fh,out cMin,out cMax,out cTop,out cScan,out cSkinBottom);HeadBox(output,x0,x1,y0,fh,out gMin,out gMax,out gTop,out gScan,out gSkinBottom);for(int y=Math.Max(y0,gTop-3);y<=Math.Min(y1,Math.Min(gSkinBottom,cSkinBottom)-7);y++){int left=x1+1,right=x0-1;for(int x=Math.Max(x0,gMin-8);x<=Math.Min(x1,gMax+8);x++)if(Identity(output.GetPixel(x,y))){left=Math.Min(left,x);right=Math.Max(right,x);}if(right>=left)for(int x=Math.Max(x0,left-3);x<=Math.Min(x1,right+3);x++)output.SetPixel(x,y,Color.Transparent);}for(int sy=Math.Max(y0,cTop-3);sy<=Math.Min(y1,cSkinBottom);sy++){int left=x1+1,right=x0-1;for(int sx=Math.Max(x0,cMin-8);sx<=Math.Min(x1,cMax+8);sx++)if(Identity(canonical.GetPixel(sx,sy))){left=Math.Min(left,sx);right=Math.Max(right,sx);}if(right>=left)for(int sx=Math.Max(x0,left-3);sx<=Math.Min(x1,right+3);sx++){Color a=canonical.GetPixel(sx,sy);if(a.A>0)output.SetPixel(sx,sy,a);}}}}
  static void RemoveSpecks(Bitmap image){int width=image.Width,height=image.Height;for(int row=0;row<3;row++)for(int col=0;col<5;col++){int x0=(int)Math.Round(col*width/5.0),x1=(int)Math.Round((col+1)*width/5.0)-1,y0=(int)Math.Round(row*height/3.0),y1=(int)Math.Round((row+1)*height/3.0)-1;bool[,] seen=new bool[x1-x0+1,y1-y0+1];int[] dx={1,-1,0,0},dy={0,0,1,-1};for(int sy=y0;sy<=y1;sy++)for(int sx=x0;sx<=x1;sx++){if(seen[sx-x0,sy-y0]||image.GetPixel(sx,sy).A==0)continue;var comp=new List<int>();var q=new Queue<int>();q.Enqueue(sy*width+sx);seen[sx-x0,sy-y0]=true;while(q.Count>0){int v=q.Dequeue(),x=v%width,y=v/width;comp.Add(v);for(int n=0;n<4;n++){int nx=x+dx[n],ny=y+dy[n];if(nx<x0||nx>x1||ny<y0||ny>y1||seen[nx-x0,ny-y0]||image.GetPixel(nx,ny).A==0)continue;seen[nx-x0,ny-y0]=true;q.Enqueue(ny*width+nx);}}if(comp.Count<24)foreach(int v in comp)image.SetPixel(v%width,v/width,Color.Transparent);}}}  static string BuildOne(string source,string canonicalPath,string outputPath){using(Bitmap output=Key(source))using(Bitmap canonical=new Bitmap(canonicalPath)){CanonicalHead(output,canonical);RemoveSpecks(output);output.Save(outputPath,ImageFormat.Png);return String.Format("{0}: {1}x{2}, aligned canonical heads",System.IO.Path.GetFileName(outputPath),output.Width,output.Height);}}
  public static string Build(string crumpledSource,string cleanSource,string canonical,string assets){return BuildOne(crumpledSource,canonical,assets+"/unused/player-sheet-clothes-barefoot-v6.png")+Environment.NewLine+BuildOne(cleanSource,canonical,assets+"/unused/player-sheet-clean-barefoot-v8.png");}
}
"@
$assets=Join-Path $ProjectRoot 'assets'
[ExactHeadRegeneratedOutfitBuilder]::Build((Join-Path $assets 'unused/player-crumpled-regenerated-key-v4.png'),(Join-Path $assets 'unused/player-clean-regenerated-key-v4.png'),(Join-Path $assets 'used/player-sheet-keyed-v1.png'),$assets)