param([string]$ProjectRoot = (Split-Path -Parent $PSScriptRoot))
$ErrorActionPreference='Stop'
Add-Type -AssemblyName System.Drawing
Add-Type -ReferencedAssemblies System.Drawing -TypeDefinition @"
using System;using System.Collections.Generic;using System.Drawing;
public static class ValidateExactWardrobe {
  static bool Skin(Color c){return c.A>0&&c.R>120&&c.G>50&&c.R-c.G>25&&c.R-c.B>35&&c.G-c.B>4;}
  static bool Hair(Color c){return c.A>0&&c.R>42&&c.R<190&&c.R>c.G*1.12&&c.G>c.B*1.03&&c.B<105;}
  static bool Identity(Color c){return Skin(c)||Hair(c);}
  static void Bounds(Bitmap image,int x0,int x1,int y0,int y1,out int minX,out int maxX,out int minY,out int maxY){minX=x1+1;maxX=x0-1;minY=y1+1;maxY=y0-1;for(int y=y0;y<=y1;y++)for(int x=x0;x<=x1;x++)if(image.GetPixel(x,y).A>0){minX=Math.Min(minX,x);maxX=Math.Max(maxX,x);minY=Math.Min(minY,y);maxY=Math.Max(maxY,y);}}
  static long CheckSheet(string path){using(Bitmap image=new Bitmap(path)){if(image.Width!=1619||image.Height!=971)throw new Exception("Unexpected dimensions: "+path);if(image.GetPixel(0,0).A!=0)throw new Exception("Background is not transparent: "+path);long opaque=0,vivid=0;for(int y=0;y<image.Height;y++)for(int x=0;x<image.Width;x++){Color c=image.GetPixel(x,y);if(c.A==0)continue;opaque++;if(c.G>195&&c.G-Math.Max(c.R,c.B)>100&&c.G>c.R*1.35&&c.G>c.B*1.35)vivid++;}if(opaque<170000)throw new Exception("Sprite content missing: "+path);if(vivid>0)throw new Exception("Chroma-key contamination: "+vivid+" pixels in "+path);for(int row=0;row<3;row++)for(int col=0;col<5;col++){int x0=(int)Math.Round(col*image.Width/5.0),x1=(int)Math.Round((col+1)*image.Width/5.0)-1,y0=(int)Math.Round(row*image.Height/3.0),y1=(int)Math.Round((row+1)*image.Height/3.0)-1,count=0;for(int y=y0;y<=y1;y+=3)for(int x=x0;x<=x1;x+=3)if(image.GetPixel(x,y).A>0)count++;if(count<500)throw new Exception("Incomplete pose row "+row+" column "+col+" in "+path);}return opaque;}}
  static long CheckHeads(string masterPath,string outfitPath){using(Bitmap master=new Bitmap(masterPath))using(Bitmap outfit=new Bitmap(outfitPath)){long matchedTotal=0;for(int row=0;row<3;row++)for(int col=0;col<5;col++){int x0=(int)Math.Round(col*master.Width/5.0),x1=(int)Math.Round((col+1)*master.Width/5.0)-1,y0=(int)Math.Round(row*master.Height/3.0),y1=(int)Math.Round((row+1)*master.Height/3.0)-1,fh=y1-y0+1,bottom=y0+(int)(fh*.245),total=0,same=0;for(int y=y0;y<=bottom;y++)for(int x=x0;x<=x1;x++){Color a=master.GetPixel(x,y);if(!Identity(a))continue;total++;if(outfit.GetPixel(x,y).ToArgb()==a.ToArgb())same++;}if(same<total*.82)throw new Exception("Canonical head is not at exact source coordinates row "+row+" column "+col+" in "+outfitPath+": "+same+"/"+total);matchedTotal+=same;}return matchedTotal;}}
  static double CheckProportions(string masterPath,string outfitPath){using(Bitmap master=new Bitmap(masterPath))using(Bitmap outfit=new Bitmap(outfitPath)){double widest=0;for(int row=0;row<3;row++)for(int col=0;col<5;col++){int x0=(int)Math.Round(col*master.Width/5.0),x1=(int)Math.Round((col+1)*master.Width/5.0)-1,y0=(int)Math.Round(row*master.Height/3.0),y1=(int)Math.Round((row+1)*master.Height/3.0)-1;int amnX,amxX,amnY,amxY,bmnX,bmxX,bmnY,bmxY;Bounds(master,x0,x1,y0,y1,out amnX,out amxX,out amnY,out amxY);Bounds(outfit,x0,x1,y0,y1,out bmnX,out bmxX,out bmnY,out bmxY);double hr=(bmxY-bmnY+1)/(double)(amxY-amnY+1),wr=(bmxX-bmnX+1)/(double)(amxX-amnX+1);if(hr<.94||hr>1.06)throw new Exception("Body height drift row "+row+" column "+col+" in "+outfitPath+": "+hr);if(wr>1.22||wr<.88)throw new Exception("Body width drift row "+row+" column "+col+" in "+outfitPath+": "+wr);widest=Math.Max(widest,wr);}return widest;}}
  static long CheckSocks(string barePath,string socksPath){using(Bitmap bare=new Bitmap(barePath))using(Bitmap socks=new Bitmap(socksPath)){long changed=0;double rh=bare.Height/3.0;for(int y=0;y<bare.Height;y++)for(int x=0;x<bare.Width;x++){Color a=bare.GetPixel(x,y),b=socks.GetPixel(x,y);if(a.ToArgb()!=b.ToArgb()){double local=y-Math.Floor(y/rh)*rh;if(local<rh*.66)throw new Exception("Sock composite changed pixels above the lower-leg band at "+x+","+y);changed++;}}if(changed<5000)throw new Exception("Sock render incomplete");return changed;}}
  public static string Run(string root){string master=root+"/player-sheet-keyed-v1.png",cr=root+"/player-sheet-clothes-barefoot-v7.png",cl=root+"/player-sheet-clean-barefoot-v9.png";long opaque=CheckSheet(cr)+CheckSheet(cl)+CheckSheet(root+"/player-sheet-underwear-socks-v6.png")+CheckSheet(root+"/player-sheet-clothes-socks-v10.png")+CheckSheet(root+"/player-sheet-clean-socks-v12.png");long heads=CheckHeads(master,cr)+CheckHeads(master,cl);double widest=Math.Max(CheckProportions(master,cr),CheckProportions(master,cl));long socks=CheckSocks(master,root+"/player-sheet-underwear-socks-v6.png")+CheckSocks(cr,root+"/player-sheet-clothes-socks-v10.png")+CheckSocks(cl,root+"/player-sheet-clean-socks-v12.png");return String.Format("opaque={0}; exact-coordinate canonical head pixels={1}; max width ratio={2:F3}; isolated sock changes={3}; all 15 poses",opaque,heads,widest,socks);}
}
"@
$assets=Join-Path $ProjectRoot 'assets'
[ValidateExactWardrobe]::Run($assets)